import postgres from 'postgres';

let connection;
function getConnection(){
  if(!connection){
    const url=process.env.STORAGE_URL||process.env.DATABASE_URL||process.env.POSTGRES_URL;
    if(!url) throw new Error('Database connection is not configured');
    connection=postgres(url,{prepare:false,ssl:'require'});
  }
  return connection;
}
export async function sql(strings,...values){
  const rows=await getConnection()(strings,...values);
  return {rows};
}

export const slots={"mon-0800":"Понедельник, 08:00 МСК","tue-0800":"Вторник, 08:00 МСК","wed-0800":"Среда, 08:00 МСК","thu-1800":"Четверг, 18:00 МСК","fri-1800":"Пятница, 18:00 МСК","sat-0600":"Суббота, 06:00 МСК"};
const schedule={"mon-0800":[1,8],"tue-0800":[2,8],"wed-0800":[3,8],"thu-1800":[4,18],"fri-1800":[5,18],"sat-0600":[6,6]};
export const json=(res,status,data)=>res.status(status).json(data);
export async function body(req){return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});}
export function code(){return crypto.randomUUID().replaceAll('-','').slice(0,20);}
export function nextInterview(slotId,now=new Date()){const [weekday,hour]=schedule[slotId]||schedule['mon-0800'];const moscow=new Date(now.getTime()+3*3600000);let days=(weekday-moscow.getUTCDay()+7)%7;if(days===0&&moscow.getUTCHours()>=hour)days=7;return new Date(Date.UTC(moscow.getUTCFullYear(),moscow.getUTCMonth(),moscow.getUTCDate()+days,hour-3)).toISOString();}
async function enablePublicApplications(){await sql`ALTER TABLE applications ENABLE ROW LEVEL SECURITY`;await sql`GRANT INSERT ON applications TO anon`;await sql`GRANT USAGE, SELECT ON SEQUENCE applications_id_seq TO anon`;try{await sql`CREATE POLICY public_candidate_insert ON applications FOR INSERT TO anon WITH CHECK (candidate_id IS NULL AND char_length(code)=20)`}catch(error){if(error?.code!=='42710')throw error}}
async function initCandidateTests(){
  await sql`CREATE TABLE IF NOT EXISTS candidate_tests (id BIGSERIAL PRIMARY KEY, candidate_id BIGINT NOT NULL, token TEXT UNIQUE NOT NULL, questionnaire_version TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', answers JSONB, sent_at TIMESTAMPTZ, submitted_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(candidate_id,questionnaire_version))`;
  await sql`ALTER TABLE candidate_tests ADD COLUMN IF NOT EXISTS completion_notice_sent_at TIMESTAMPTZ`;
  await sql`ALTER TABLE candidate_tests ADD COLUMN IF NOT EXISTS opened_at TIMESTAMPTZ`;
  await sql`CREATE TABLE IF NOT EXISTS candidate_test_attempt_archive (id BIGSERIAL PRIMARY KEY,candidate_test_id BIGINT NOT NULL,candidate_id BIGINT NOT NULL,questionnaire_version TEXT NOT NULL,answers JSONB,sent_at TIMESTAMPTZ,submitted_at TIMESTAMPTZ,archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS candidate_test_files (id BIGSERIAL PRIMARY KEY,candidate_id BIGINT NOT NULL,test_type TEXT NOT NULL DEFAULT 'test_1',file_kind TEXT NOT NULL,file_name TEXT NOT NULL,mime_type TEXT NOT NULL,file_data TEXT NOT NULL,uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(candidate_id,test_type,file_kind))`;
  await sql`ALTER TABLE candidate_tests ENABLE ROW LEVEL SECURITY`;
  await sql`REVOKE ALL ON candidate_tests FROM anon`;
  await sql`REVOKE ALL ON candidate_tests FROM authenticated`;
  await sql`CREATE OR REPLACE FUNCTION get_candidate_test(p_token TEXT) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE item candidate_tests%ROWTYPE; result JSONB; opened_id BIGINT; BEGIN SELECT * INTO item FROM candidate_tests WHERE token=p_token LIMIT 1; IF item.id IS NULL THEN RETURN NULL; END IF; UPDATE candidate_tests SET opened_at=NOW(),updated_at=NOW() WHERE id=item.id AND opened_at IS NULL RETURNING id INTO opened_id; IF opened_id IS NOT NULL THEN INSERT INTO messages(candidate_id,direction,kind,text,delivery_status) VALUES(item.candidate_id,'in','link_open','Открыл тест 1 по кнопке или ссылке','received'); END IF; SELECT jsonb_build_object('candidate_name',COALESCE(NULLIF(a.full_name,''),NULLIF(concat_ws(' ',c.first_name,c.last_name),''),c.username,'Кандидат'),'city',c.city,'telegram_username',c.username,'questionnaire_version',t.questionnaire_version,'submitted_at',t.submitted_at,'status',t.status) INTO result FROM candidate_tests t JOIN candidates c ON c.id=t.candidate_id LEFT JOIN applications a ON a.candidate_id=c.id WHERE t.id=item.id; RETURN result; END $$`;
  await sql`CREATE OR REPLACE FUNCTION submit_candidate_test(p_token TEXT,p_answers JSONB,p_questionnaire_version TEXT) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE changed_id BIGINT; changed_candidate_id BIGINT; BEGIN IF p_questionnaire_version IS NULL OR p_questionnaire_version<>'executive-effectiveness-2020-ru-v1' THEN RETURN jsonb_build_object('ok',false,'error','Версия теста не совпадает'); END IF; IF p_answers IS NULL OR jsonb_typeof(p_answers)<>'array' THEN RETURN jsonb_build_object('ok',false,'error','Нужно ответить на все 200 вопросов'); END IF; IF jsonb_array_length(p_answers)<>200 THEN RETURN jsonb_build_object('ok',false,'error','Нужно ответить на все 200 вопросов'); END IF; IF EXISTS(SELECT 1 FROM jsonb_array_elements_text(p_answers) AS answer(value) WHERE answer.value NOT IN ('+','M','-')) THEN RETURN jsonb_build_object('ok',false,'error','Допустимы только ответы +, М или −'); END IF; UPDATE candidate_tests SET answers=p_answers,status='completed',submitted_at=NOW(),updated_at=NOW() WHERE token=p_token AND questionnaire_version=p_questionnaire_version AND submitted_at IS NULL RETURNING id,candidate_id INTO changed_id,changed_candidate_id; IF changed_id IS NULL THEN IF EXISTS(SELECT 1 FROM candidate_tests WHERE token=p_token AND submitted_at IS NOT NULL) THEN RETURN jsonb_build_object('ok',false,'error','Тест уже отправлен'); END IF; RETURN jsonb_build_object('ok',false,'error','Персональная ссылка не найдена'); END IF; UPDATE candidates SET status='test_1_completed',updated_at=NOW() WHERE id=changed_candidate_id AND status NOT IN ('test_1_passed','training','internship','hired','rejected','cancelled'); RETURN jsonb_build_object('ok',true,'submission_id',changed_id,'candidate_status','test_1_completed'); END $$`;
  await sql`REVOKE ALL ON FUNCTION get_candidate_test(TEXT) FROM PUBLIC`;
  await sql`REVOKE ALL ON FUNCTION submit_candidate_test(TEXT,JSONB,TEXT) FROM PUBLIC`;
  await sql`GRANT EXECUTE ON FUNCTION get_candidate_test(TEXT) TO anon,authenticated`;
  await sql`GRANT EXECUTE ON FUNCTION submit_candidate_test(TEXT,JSONB,TEXT) TO anon,authenticated`;
  await sql`CREATE TABLE IF NOT EXISTS candidate_questionnaire_two(id BIGSERIAL PRIMARY KEY,candidate_id BIGINT UNIQUE NOT NULL,token TEXT UNIQUE NOT NULL,status TEXT NOT NULL DEFAULT 'pending',answers JSONB,sent_at TIMESTAMPTZ,submitted_at TIMESTAMPTZ,completion_notice_sent_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
  await sql`ALTER TABLE candidate_questionnaire_two ADD COLUMN IF NOT EXISTS opened_at TIMESTAMPTZ`;
  await sql`ALTER TABLE candidate_questionnaire_two ENABLE ROW LEVEL SECURITY`;
  await sql`REVOKE ALL ON candidate_questionnaire_two FROM anon`;
  await sql`REVOKE ALL ON candidate_questionnaire_two FROM authenticated`;
  await sql`CREATE OR REPLACE FUNCTION get_candidate_questionnaire_two(p_token TEXT) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE item candidate_questionnaire_two%ROWTYPE; result JSONB; opened_id BIGINT; BEGIN SELECT * INTO item FROM candidate_questionnaire_two WHERE token=p_token LIMIT 1; IF item.id IS NULL THEN RETURN NULL; END IF; UPDATE candidate_questionnaire_two SET opened_at=NOW(),updated_at=NOW() WHERE id=item.id AND opened_at IS NULL RETURNING id INTO opened_id; IF opened_id IS NOT NULL THEN INSERT INTO messages(candidate_id,direction,kind,text,delivery_status) VALUES(item.candidate_id,'in','link_open','Открыл Анкету 2 по кнопке или ссылке','received'); END IF; SELECT jsonb_build_object('candidate_name',COALESCE(NULLIF(a.full_name,''),NULLIF(concat_ws(' ',c.first_name,c.last_name),''),c.username,'Кандидат'),'city',c.city,'telegram_username',c.username,'submitted_at',q.submitted_at,'status',q.status) INTO result FROM candidate_questionnaire_two q JOIN candidates c ON c.id=q.candidate_id LEFT JOIN applications a ON a.candidate_id=c.id WHERE q.id=item.id; RETURN result; END $$`;
  await sql`CREATE OR REPLACE FUNCTION submit_candidate_questionnaire_two(p_token TEXT,p_answers JSONB) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE changed_id BIGINT; changed_candidate_id BIGINT; BEGIN IF p_answers IS NULL OR jsonb_typeof(p_answers)<>'object' THEN RETURN jsonb_build_object('ok',false,'error','Заполните обязательные поля'); END IF; IF COALESCE(p_answers->>'work_history','')='' OR COALESCE(p_answers->>'achievements','')='' OR COALESCE(p_answers->>'strengths','')='' OR COALESCE(p_answers->>'development','')='' OR COALESCE(p_answers->>'hobbies','')='' OR COALESCE(p_answers->>'goals','')='' OR COALESCE(p_answers->>'readiness','')='' OR COALESCE(p_answers->>'income','')='' THEN RETURN jsonb_build_object('ok',false,'error','Заполните обязательные поля'); END IF; UPDATE candidate_questionnaire_two SET answers=p_answers,status='completed',submitted_at=NOW(),updated_at=NOW() WHERE token=p_token AND submitted_at IS NULL RETURNING id,candidate_id INTO changed_id,changed_candidate_id; IF changed_id IS NULL THEN RETURN jsonb_build_object('ok',false,'error','Анкета уже отправлена или ссылка недействительна'); END IF; UPDATE candidates SET status='questionnaire',updated_at=NOW() WHERE id=changed_candidate_id AND status IN ('new','interview_booked','interviewed'); RETURN jsonb_build_object('ok',true,'submission_id',changed_id,'candidate_status','questionnaire'); END $$`;
  await sql`REVOKE ALL ON FUNCTION get_candidate_questionnaire_two(TEXT) FROM PUBLIC`;
  await sql`REVOKE ALL ON FUNCTION submit_candidate_questionnaire_two(TEXT,JSONB) FROM PUBLIC`;
  await sql`GRANT EXECUTE ON FUNCTION get_candidate_questionnaire_two(TEXT) TO anon,authenticated`;
  await sql`GRANT EXECUTE ON FUNCTION submit_candidate_questionnaire_two(TEXT,JSONB) TO anon,authenticated`;
}
async function initCandidateDrive(){
  await sql`ALTER TABLE candidates ADD COLUMN IF NOT EXISTS group_joined_at TIMESTAMPTZ`;
  await sql`CREATE TABLE IF NOT EXISTS candidate_drive(candidate_id BIGINT PRIMARY KEY,folder_id TEXT NOT NULL,folder_url TEXT NOT NULL,folder_name TEXT NOT NULL,synced_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS candidate_drive_files(id BIGSERIAL PRIMARY KEY,candidate_id BIGINT NOT NULL,file_kind TEXT NOT NULL,file_name TEXT NOT NULL,file_url TEXT NOT NULL,drive_file_id TEXT NOT NULL,mime_type TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(candidate_id,file_kind))`;
}

async function initOfflineInterviews(){
  await sql`CREATE TABLE IF NOT EXISTS offline_interview_invites(candidate_id BIGINT NOT NULL,event_date DATE NOT NULL,status TEXT NOT NULL DEFAULT 'pending',telegram_message_id TEXT,sent_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(candidate_id,event_date))`;
  await sql`CREATE TABLE IF NOT EXISTS offline_interview_bookings(candidate_id BIGINT NOT NULL,event_date DATE NOT NULL,slot_time TEXT NOT NULL,slot_position INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'booked',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(candidate_id,event_date),UNIQUE(event_date,slot_time,slot_position))`;
}

export async function init(){await sql`CREATE TABLE IF NOT EXISTS applications (id BIGSERIAL PRIMARY KEY, code TEXT UNIQUE NOT NULL, full_name TEXT NOT NULL, age TEXT, city TEXT NOT NULL, motivation TEXT NOT NULL, phone TEXT, slot_id TEXT, source_id TEXT NOT NULL DEFAULT 'direct', garcia_confirmed BOOLEAN NOT NULL DEFAULT FALSE, test_answer TEXT NOT NULL, candidate_id BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`ALTER TABLE applications ALTER COLUMN slot_id DROP NOT NULL`;await sql`ALTER TABLE applications ADD COLUMN IF NOT EXISTS trainer_experience_level TEXT`;await enablePublicApplications();await sql`CREATE TABLE IF NOT EXISTS candidates (id BIGSERIAL PRIMARY KEY, chat_id TEXT UNIQUE NOT NULL, username TEXT, first_name TEXT, last_name TEXT, phone TEXT, city TEXT, slot_id TEXT, interview_at TIMESTAMPTZ, source_id TEXT NOT NULL DEFAULT 'direct', status TEXT NOT NULL DEFAULT 'new', consent BOOLEAN NOT NULL DEFAULT TRUE, reminded_30m BOOLEAN NOT NULL DEFAULT FALSE, no_show_followup_sent BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`ALTER TABLE candidates ADD COLUMN IF NOT EXISTS no_show_followup_sent BOOLEAN NOT NULL DEFAULT FALSE`;await sql`CREATE TABLE IF NOT EXISTS messages (id BIGSERIAL PRIMARY KEY, candidate_id BIGINT NOT NULL, direction TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'text', text TEXT NOT NULL, delivery_status TEXT NOT NULL DEFAULT 'pending', telegram_message_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`CREATE TABLE IF NOT EXISTS broadcasts (id BIGSERIAL PRIMARY KEY, text TEXT NOT NULL, status_filter TEXT, source_filter TEXT, city_filter TEXT, sent_count INTEGER NOT NULL DEFAULT 0, failed_count INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`ALTER TABLE broadcasts ADD COLUMN IF NOT EXISTS city_filter TEXT`;await sql`CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`CREATE TABLE IF NOT EXISTS hr_brief_deliveries (candidate_id BIGINT NOT NULL, interview_at TIMESTAMPTZ NOT NULL, chat_id TEXT NOT NULL, thread_id TEXT NOT NULL DEFAULT '', telegram_message_id TEXT, delivered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(candidate_id,interview_at,chat_id,thread_id))`;await sql`CREATE TABLE IF NOT EXISTS interview_brief_deliveries (interview_at TIMESTAMPTZ NOT NULL, slot_id TEXT NOT NULL, chat_id TEXT NOT NULL, thread_id TEXT NOT NULL DEFAULT '', telegram_message_id TEXT, delivered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(interview_at,chat_id,thread_id))`;await initCandidateTests();await initCandidateDrive();await initOfflineInterviews();}
export async function telegramApi(method,payload={}){const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error('Telegram bot token is not configured');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!data.ok)throw new Error(data.description||`Telegram ${method} failed`);return data.result;}
export async function telegram(chatId,text,extra={}){const result=await telegramApi('sendMessage',{chat_id:chatId,text,parse_mode:'HTML',...extra});return result?.message_id;}
export async function ensureTelegramWebhook(req){const token=process.env.TELEGRAM_BOT_TOKEN,secret=process.env.TELEGRAM_WEBHOOK_SECRET;if(!token||!secret)return;const host=req.headers['x-forwarded-host']||req.headers.host;if(!host)return;await fetch(`https://api.telegram.org/bot${token}/setWebhook`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:`https://${host}/api/telegram`,secret_token:secret,allowed_updates:['message','callback_query','chat_member']})});}
export function operator(req){const expected=process.env.OPERATOR_ACCESS_KEY;if(!expected||req.headers.authorization!==`Bearer ${expected}`)return false;return true;}





