const API='/api/operator';
const statuses=[['new','Новый'],['interview_booked','Записан'],['interviewed','Собеседование'],['training','Обучение'],['internship','Стажировка'],['hired','Принят'],['rejected','Отказ'],['cancelled','Отменил']];
const slots={'mon-0800':'Пн 08:00','tue-0800':'Вт 08:00','wed-0800':'Ср 08:00','thu-1800':'Чт 18:00','fri-1800':'Пт 18:00','sat-0600':'Сб 06:00'};
const accessFromLink=new URLSearchParams(location.hash.slice(1)).get('access')||'';
let key=sessionStorage.getItem('operatorKey')||accessFromLink,all=[],selected=null,details=null,messages=[];
if(accessFromLink)history.replaceState(null,'',location.pathname+location.search);
const $=id=>document.getElementById(id), label=v=>statuses.find(x=>x[0]===v)?.[1]||v,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
statuses.forEach(([v,l])=>$('filter').add(new Option(l,v)));
Object.entries(slots).forEach(([v,l])=>$('slotFilter').add(new Option(l,v)));
async function api(method='GET',body,url=API){const r=await fetch(url,{method,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка соединения');return d}
function showNotice(t){$('notice').textContent=t;$('notice').style.display='block';setTimeout(()=>$('notice').style.display='none',4000)}
async function login(k){key=k;try{await load();sessionStorage.setItem('operatorKey',key);$('login').hidden=true;$('panel').hidden=false}catch(e){key='';sessionStorage.removeItem('operatorKey');$('loginError').textContent=e.message}}
function fillDynamicFilter(id,placeholder,values){const select=$(id),current=select.value;select.innerHTML='';select.add(new Option(placeholder,''));values.filter(Boolean).sort((a,b)=>a.localeCompare(b,'ru')).forEach(v=>select.add(new Option(v,v)));select.value=[...select.options].some(o=>o.value===current)?current:''}
function interviewDate(c){if(!c.interview_at)return'';const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(c.interview_at));const get=t=>parts.find(p=>p.type===t)?.value||'';return `${get('year')}-${get('month')}-${get('day')}`}
function interviewLabel(c){return c.interview_at?new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(c.interview_at))+' МСК':'Дата не назначена'}
function fillDateFilter(){const select=$('interviewDateFilter'),current=select.value,dates=[...new Set(all.map(interviewDate).filter(Boolean))].sort();select.innerHTML='';select.add(new Option('Все даты Zoom',''));dates.forEach(v=>select.add(new Option(new Date(v+'T12:00:00Z').toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'}),v)));select.value=[...select.options].some(o=>o.value===current)?current:''}
async function load(){const d=await api();all=d.candidates||[];fillDynamicFilter('cityFilter','Все города',[...new Set(all.map(c=>c.city))]);fillDynamicFilter('sourceFilter','Все источники',[...new Set(all.map(c=>c.source_id))]);fillDateFilter();renderList()}
function renderList(){const q=$('search').value.toLowerCase(),f=$('filter').value,city=$('cityFilter').value,source=$('sourceFilter').value,date=$('interviewDateFilter').value,slot=$('slotFilter').value;const shown=all.filter(c=>(!f||c.status===f)&&(!city||c.city===city)&&(!source||c.source_id===source)&&(!date||interviewDate(c)===date)&&(!slot||c.slot_id===slot)&&`${c.first_name||''} ${c.last_name||''} ${c.username||''} ${c.phone||''}`.toLowerCase().includes(q)).sort((a,b)=>(a.interview_at?new Date(a.interview_at).getTime():Number.MAX_SAFE_INTEGER)-(b.interview_at?new Date(b.interview_at).getTime():Number.MAX_SAFE_INTEGER));$('count').textContent=`Кандидатов: ${shown.length}`;$('candidates').innerHTML=shown.map(c=>`<button class="row ${selected===c.id?'active':''}" data-id="${c.id}"><span><strong>${esc(c.first_name||c.username||'Кандидат '+c.id)} ${esc(c.last_name)}</strong><br><small>@${esc(c.username||'без username')} · ${esc(c.city||'город не указан')} · ${esc(c.source_id)}</small></span><span><b>${esc(interviewLabel(c))}</b><br><small>${esc(slots[c.slot_id]||'Без слота')} · ${esc(label(c.status))}</small></span><em>${esc(c.last_message||'Нет сообщений')}</em></button>`).join('');document.querySelectorAll('.row').forEach(b=>b.onclick=()=>openCandidate(+b.dataset.id))}
async function openCandidate(id){selected=id;const d=await api('GET',null,`${API}?candidate_id=${id}`);details=d.candidate;messages=d.messages||[];renderList();renderDetail()}
function renderDetail(){const c=details;if(!c)return;const personalChat=c.username?`<a class="telegram-link" href="https://t.me/${encodeURIComponent(c.username)}" target="_blank" rel="noopener">Написать лично в Telegram</a>`:'<p class="muted">У кандидата нет публичного Telegram username. Напишите ему через бота ниже.</p>';$('detail').innerHTML=`<div class="candidate-head"><div><h2>${esc(c.first_name||c.username||'Кандидат')} ${esc(c.last_name)}</h2><p>@${esc(c.username||'—')} · ${esc(c.phone||'телефон не указан')} · ${esc(c.city||'город не указан')} · ${esc(slots[c.slot_id]||'слот не выбран')}</p>${c.motivation?`<p><b>Мотивация:</b> ${esc(c.motivation)}${c.age?' · Возраст: '+esc(c.age):''}</p>`:''}<p class="garcia-status ${c.garcia_confirmed?'yes':'no'}"><b>Вы такой человек?</b> ${c.test_answer==='Послание к Гарсии: да'?'✓ Да':c.test_answer==='Послание к Гарсии: нет'?'○ Нет':'— Раньше не запрашивалось'}</p>${personalChat}</div><select id="status">${statuses.map(([v,l])=>`<option value="${v}" ${v===c.status?'selected':''}>${l}</option>`).join('')}</select></div><div class="history">${messages.map(m=>`<div class="bubble ${m.direction==='out'?'out':'in'}"><p>${esc(m.text)}</p><small>${new Date(m.created_at).toLocaleString('ru-RU')} · ${esc(m.delivery_status)}</small></div>`).join('')||'<p class="muted">Сообщений пока нет</p>'}</div><div class="reply"><textarea id="replyText" placeholder="Написать кандидату через бота…"></textarea><button id="replySend">Отправить через бота</button></div>`;$('status').onchange=async e=>{await api('PATCH',{candidateId:c.id,status:e.target.value});showNotice('Статус сохранён');await load()};$('replySend').onclick=sendReply}
async function sendReply(){const text=$('replyText').value.trim();if(!text)return;await api('POST',{candidateId:selected,text});$('replyText').value='';showNotice('Сообщение отправлено');await openCandidate(selected)}
$('loginForm').onsubmit=e=>{e.preventDefault();login($('key').value.trim())};$('logout').onclick=()=>{sessionStorage.clear();location.reload()};$('refresh').onclick=load;$('search').oninput=renderList;['filter','cityFilter','sourceFilter','interviewDateFilter','slotFilter'].forEach(id=>$(id).onchange=renderList);
$('broadcastSend').onclick=async()=>{const text=$('broadcastText').value.trim();if(!text)return;const body={text,statusFilter:$('filter').value||undefined,cityFilter:$('cityFilter').value||undefined,sourceFilter:$('sourceFilter').value||undefined,interviewDateFilter:$('interviewDateFilter').value||undefined,slotFilter:$('slotFilter').value||undefined};const p=await api('POST',{...body,preview:true});if(!p.recipientCount){showNotice('По выбранным фильтрам нет получателей');return}if(!confirm(`Отправить сообщение ${p.recipientCount} кандидатам?`))return;const d=await api('POST',body);$('broadcastText').value='';await load();if(selected)await openCandidate(selected);showNotice(d.historyFailed?`Доставлено: ${d.sent}, но не записано в историю: ${d.historyFailed}`:`Доставлено: ${d.sent}, ошибок: ${d.failed}`)};
if(key)login(key);
