import {test,mock} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite(),sent=[],tasks=new Map(),effects=new Map(),answers=[];
await db.exec(`CREATE TABLE candidates(id bigint PRIMARY KEY,chat_id text,first_name text,last_name text,city text,status text,consent boolean,interview_at timestamptz,slot_id text,username text);
CREATE TABLE app_settings(key text PRIMARY KEY,value text);
CREATE TABLE candidate_questionnaire_two(candidate_id bigint,sent_at timestamptz);
CREATE TABLE messages(candidate_id bigint,direction text,kind text,text text,delivery_status text,telegram_message_id text);
CREATE TABLE offline_interview_bookings(candidate_id bigint,event_date date,slot_time text,status text);
CREATE TABLE applications(id bigint,candidate_id bigint,full_name text,trainer_experience_level text,created_at timestamptz);
CREATE TABLE candidate_drive(candidate_id bigint,folder_url text);
INSERT INTO candidates VALUES(1,'101','Имя','','Минск','interview_booked',true,'2026-09-01T08:00:00Z','tue-0800','one'),(2,'102','Старый','','Минск','questionnaire',true,'2026-08-25T05:00:00Z','tue-0800','old'),(3,'103','Другой','','Челябинск','test_1_completed',true,'2026-08-25T05:00:00Z','tue-0800','three');
INSERT INTO candidate_questionnaire_two VALUES(2,'2026-01-01');
INSERT INTO app_settings VALUES('zoom_meeting_url','https://zoom.us/primary'),('hr_brief_chat_id','staff'),('hr_brief_thread_id','7');`);
await mock.module('../api/_core.js',{namedExports:{sql:(s,...v)=>db.query(s.reduce((a,b,i)=>a+(i?'$'+i:'')+b,''),v),telegram:async(chat,text,extra)=>{sent.push({chat,text,extra});return sent.length;},telegramApi:async(method,p)=>answers.push({method,p})}});
await mock.module('../lib/funnel-store.js',{namedExports:{initFunnel:async()=>{},createTask:async(kind,payload,due,id)=>{tasks.set(id,{kind,payload,due});},effect:async(key,fn)=>{if(effects.has(key))return effects.get(key);const value=await fn();effects.set(key,value);return value;}}});
const {initPrimaryEvidence,primaryAccess,handlePrimaryEntry,requirePrimaryAccess,reportPrimaryEntry}=await import('../lib/primary-evidence.js');
const {scheduleMinskReminder,runMinskReminder}=await import('../lib/review-reminders.js');
test('entry: gate before click, retain legacy, authenticate private owner, record first click once, report once',async()=>{
 await initPrimaryEvidence();assert.equal((await primaryAccess(1)).allowed,false);assert.equal((await primaryAccess(2)).legacy,true);
 assert.equal(await requirePrimaryAccess({id:1,chat_id:'101',status:'interview_booked'}),false);
 assert.equal(sent[0].extra.reply_markup.inline_keyboard[0][0].callback_data,'primary_zoom_enter');
 const cb={data:'primary_zoom_enter',id:'cb1',from:{id:101},message:{chat:{id:102,type:'private'}}};
 await handlePrimaryEntry(cb);assert.equal((await primaryAccess(1)).allowed,false);
 cb.message.chat.id=101;
 await db.exec(`UPDATE candidates SET interview_at=NOW()+INTERVAL '7 days' WHERE id=1`);
 await handlePrimaryEntry({...cb,id:'early'});assert.equal((await primaryAccess(1)).allowed,false);assert.equal(tasks.size,0);
 await db.exec(`UPDATE candidates SET interview_at=NOW()-INTERVAL '61 minutes' WHERE id=1`);
 await handlePrimaryEntry({...cb,id:'late'});assert.equal((await primaryAccess(1)).allowed,false);
 await db.exec(`UPDATE candidates SET interview_at=NOW() WHERE id=1`);
 await handlePrimaryEntry(cb);const at=(await primaryAccess(1)).clickedAt;assert.ok(at);
 await handlePrimaryEntry(cb);assert.equal((await primaryAccess(1)).clickedAt.getTime(),at.getTime());
 assert.equal(tasks.size,1);assert.equal(sent.filter(s=>s.text.startsWith('Подключитесь')).length,3);
 assert.equal((await db.query('SELECT status FROM candidates WHERE id=1')).rows[0].status,'interview_booked');
 await reportPrimaryEntry(1);await reportPrimaryEntry(1);assert.equal(sent.filter(s=>s.chat==='staff').length,1);assert.match(sent.at(-1).text,/не подтверждение присутствия/);
});
test('review reminds every booked city including Chelyabinsk; sends once with correct URL',async()=>{
 mock.timers.enable({apis:['Date'],now:new Date('2026-09-01T07:30:00Z')});
 await db.exec(`UPDATE candidates SET status='test_1_completed' WHERE id=1;INSERT INTO offline_interview_bookings VALUES(1,'2026-09-01','1100','booked'),(3,'2026-09-01','1100','booked');`);
 await scheduleMinskReminder('1100');await scheduleMinskReminder('1100');assert.equal([...tasks.values()].filter(x=>x.kind==='minsk_review_30m').length,1);
 await assert.rejects(scheduleMinskReminder('1400'));
 const before=sent.length;await runMinskReminder({date:'2026-09-01',slot:'1100'});await runMinskReminder({date:'2026-09-01',slot:'1100'});
 assert.equal(sent.length-before,3);assert.equal(sent[before].chat,'101');assert.equal(sent[before+1].chat,'103');assert.match(sent[before].extra.reply_markup.inline_keyboard[0][0].url,/8954571284/);
 assert.equal(sent.at(-1).extra.message_thread_id,30);assert.match(sent.at(-1).text,/Записано: 2/);assert.match(sent.at(-1).extra.reply_markup.inline_keyboard[0][0].url,/candidate_id=1/);
 assert.equal((await db.query("SELECT * FROM messages WHERE kind='review_reminder_30m'")).rows.length,2);
 mock.timers.setTime(new Date('2026-09-01T09:00:00Z').getTime());assert.deepEqual(await scheduleMinskReminder('1100'),{expired:true});
 await db.close();mock.timers.reset();
});
